# CSC 593

## Week 7

### Merge Errors

#### Not resolved automatically
`git checkout --ours homework/Assignment\ 5.ipynb`  
`git commit -a -m 'Fixing merge.'`

#### Resolved automatically (vim)
`:wq`

### Pandas 2

In [3]:
import numpy as np
import pandas as pd

The BRFSS (Behavioral Risk Factor Surveillance System) data is too big to put into Github. This cell downloads it from the CDC's website and unzips it into your `data` folder.

In [4]:
#Setup for examples.
from urllib.request import urlretrieve
import zipfile
from pathlib import Path

zf = '../data/brfss/LLCP2018ASC.zip'
if not Path(zf).exists():
    Path('../data/brfss').mkdir(exist_ok=True)

    urlretrieve('https://www.cdc.gov/brfss/annual_data/2018/pdf/overview-2018-508.pdf', '../data/brfss/overview-2018-508.pdf')
    urlretrieve('https://www.cdc.gov/brfss/annual_data/2018/pdf/codebook18_llcp-v2-508.pdf', '../data/brfss/codebook18_llcp-v2-508.pdf')
    
    urlretrieve('https://www.cdc.gov/brfss/annual_data/2018/files/LLCP2018ASC.zip', zf)

fwff = '../data/brfss/LLCP2018.ASC'
if not Path(fwff).exists():
    with zipfile.ZipFile(zf) as z:
        z.extractall('../data/brfss')

Load the BRFSS data and set a couple of data types explicitly. (More supported data types are listed at https://docs.scipy.org/doc/numpy/user/basics.types.html)

In [25]:
names= ['state', 'imonth', 'iday', 
        'iyear', 'dispcode','genhlth', 
        'physhlth',
        'menthlth', 'poorhlth', 'hlthpln1',
        'persdoc2', 'medcost', 'checkup1',
        'WEIGHT2', 'HEIGHT3']
cols = [
    (1, 3),
    (18, 20),
    (20, 22),
    (22, 27),
    (31, 35),
    (89, 90),
    (90, 92),
    (92, 94),
    (94, 96),
    (96, 97),
    (97, 98),
    (98, 99),
    (99, 100),
    (176, 180),
    (180, 184)
]
types= {
    'WEIGHT2': str,
    'HEIGHT3': str,
}
brfss = pd.read_fwf(fwff + ' ', 
                    names=names,
                    colspecs=cols,
                    dtype=types)

#### Searching

In [26]:
#Get an individual column.
brfss.WEIGHT2

0         0130
1         0200
2         0142
3         0190
4         7777
5         0172
6         0150
7         0130
8         0205
9         0151
10        0199
11        0170
12        0160
13        0200
14        0285
15        0217
16        0230
17        0250
18        0155
19        0138
20        0240
21        0240
22        0185
23        0165
24        0131
25        0119
26        0180
27        0169
28        0128
29        0218
          ...
437406     NaN
437407    0320
437408    0125
437409    0158
437410    0155
437411    0150
437412    0138
437413    0135
437414    0178
437415    0126
437416    0115
437417    0183
437418    0153
437419    0138
437420    0260
437421    0160
437422    0200
437423    0126
437424    0340
437425    0298
437426    0160
437427    0160
437428    0163
437429    0172
437430    0170
437431    0098
437432    7777
437433    0156
437434    0137
437435    0192
Name: WEIGHT2, Length: 437436, dtype: object

In [7]:
#For multiple columns, use a list as a subscript.
brfss[['WEIGHT2', 'HEIGHT3']]

       WEIGHT2 HEIGHT3
0         0130    0504
1         0200    0505
2         0142    0410
3         0190    0510
4         7777    0503
5         0172    0502
6         0150    0505
7         0130    0505
8         0205    0601
9         0151    0503
10        0199    0600
11        0170    0503
12        0160    0503
13        0200    0504
14        0285    0511
15        0217    0506
16        0230    0509
17        0250    0601
18        0155    0504
19        0138    0504
20        0240    0507
21        0240    0504
22        0185    0505
23        0165    0509
24        0131    0504
25        0119    0502
26        0180    0505
27        0169    0506
28        0128    0506
29        0218    0603
...        ...     ...
437406     NaN     NaN
437407    0320    0603
437408    0125    0501
437409    0158    0505
437410    0155    0502
437411    0150    0506
437412    0138    0502
437413    0135    0506
437414    0178    0506
437415    0126    0506
437416    0115    0411
437417    0183    0503
437418    0153    0504
437419    0138    0500
437420    0260    0503
437421    0160    0507
437422    0200    0601
437423    0126    0500
437424    0340    0507
437425    0298    0600
437426    0160    0508
437427    0160    0506
437428    0163    0502
437429    0172    0508
437430    0170    0503
437431    0098    0502
437432    7777    0502
437433    0156    0500
437434    0137    0501
437435    0192    0510

[437436 rows x 2 columns]

The `loc()` and `iloc()` methods (see the table on p. 144-5 of *Python for Data Analysis*)

In [8]:
#Get the first row.
brfss.loc[0]

state          1
imonth         1
iday           5
iyear       2018
dispcode    1100
genhlth        2
physhlth      30
menthlth      88
poorhlth      30
hlthpln1       1
persdoc2       1
medcost        2
checkup1       1
WEIGHT2     0130
HEIGHT3     0504
Name: 0, dtype: object

In [9]:
#Get WEIGHT2 from the third row.
brfss.loc[2, 'WEIGHT2']

'0142'

In [10]:
#Same thing, but using the integer index instead of the column name.
brfss.iloc[2,-2]

'0142'

In [11]:
brfss.at[2, 'WEIGHT2']

'0142'

In [27]:
brfss.iat[2, -2]

'0142'

In [13]:
brfss.loc[:100, ['HEIGHT3', 'WEIGHT2']]

    HEIGHT3 WEIGHT2
0      0504    0130
1      0505    0200
2      0410    0142
3      0510    0190
4      0503    7777
5      0502    0172
6      0505    0150
7      0505    0130
8      0601    0205
9      0503    0151
10     0600    0199
11     0503    0170
12     0503    0160
13     0504    0200
14     0511    0285
15     0506    0217
16     0509    0230
17     0601    0250
18     0504    0155
19     0504    0138
20     0507    0240
21     0504    0240
22     0505    0185
23     0509    0165
24     0504    0131
25     0502    0119
26     0505    0180
27     0506    0169
28     0506    0128
29     0603    0218
..      ...     ...
71     0503    7777
72     0506    0150
73     0506    0160
74     0601    0232
75     0508    0222
76     0510    0210
77     0500    0170
78     0500    0237
79     0505    0188
80     0505    0125
81     0506    0180
82     0509    0180
83     0500    0160
84     0507    0225
85     0506    0160
86     0506    0160
87     0500    0120
88     0510    0228
89     0508    0205
90     0502    9999
91     0600    0235
92     0502    0142
93     0511    0210
94     0509    0182
95     0508    0220
96     0410    0125
97     0600    0190
98     0600    0200
99     0507    0170
100    0510    0200

[101 rows x 2 columns]

In [29]:
brfss['WEIGHT2'] == '9999'

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
437406    False
437407    False
437408    False
437409    False
437410    False
437411    False
437412    False
437413    False
437414    False
437415    False
437416    False
437417    False
437418    False
437419    False
437420    False
437421    False
437422    False
437423    False
437424    False
437425    False
437426    False
437427    False
437428    False
437429    False
437430    False
437431    False
437432    False
437433    False
437434    False
437435    False
Name: WEIGHT2, Length: 437436, dtype: bool

In [28]:
#Find rows based on a value
brfss[brfss['WEIGHT2']=='9999']

,state,imonth,iday,iyear,dispcode,genhlth,physhlth,menthlth,poorhlth,hlthpln1,persdoc2,medcost,checkup1,WEIGHT2,HEIGHT3
61,1,2,1,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,9999
69,1,2,1,2018,1100,4.0,30.0,88.0,30.0,1.0,1.0,2.0,1.0,9999,0506
90,1,2,3,2018,1100,1.0,88.0,14.0,4.0,1.0,1.0,2.0,1.0,9999,0502
118,1,3,5,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,0501
129,1,3,15,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,9999
137,1,1,13,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,0410
159,1,1,11,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,9999
162,1,1,8,2018,1100,3.0,88.0,14.0,14.0,1.0,2.0,2.0,3.0,9999,0508
172,1,1,25,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,0504
191,1,2,3,2018,1100,4.0,30.0,88.0,15.0,1.0,2.0,2.0,1.0,9999,0504
231,1,3,1,2018,1100,5.0,30.0,15.0,30.0,1.0,1.0,1.0,1.0,9999,0504
234,1,3,12,2018,1100,4.0,20.0,10.0,25.0,1.0,1.0,2.0,1.0,9999,0505
271,1,1,11,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,0503
296,1,1,8,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,0503
320,1,3,1,2018,1100,2.0,10.0,88.0,7.0,1.0,1.0,2.0,1.0,9999,0503
324,1,2,2,2018,1200,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,0506
347,1,3,24,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,9999
465,1,3,2,2018,1100,4.0,15.0,88.0,10.0,1.0,1.0,2.0,1.0,9999,0502
475,1,3,22,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,9999
529,1,3,6,2018,1200,3.0,99.0,88.0,88.0,1.0,2.0,2.0,1.0,9999,0505
534,1,2,14,2018,1100,5.0,30.0,88.0,88.0,1.0,1.0,2.0,1.0,9999,9999
573,1,3,28,2018,1100,2.0,88.0,88.0,NaN,1.0,3.0,2.0,1.0,9999,0500
590,1,1,11,2018,1100,3.0,3.0,7.0,88.0,1.0,1.0,2.0,1.0,9999,0503
678,1,3,2,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,9999
694,1,1,23,2018,1200,2.0,7.0,5.0,5.0,1.0,3.0,1.0,4.0,9999,0507
719,1,2,27,2018,1100,5.0,20.0,15.0,20.0,1.0,1.0,2.0,1.0,9999,0505
728,1,2,15,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,2.0,9999,7777
744,1,3,1,2018,1100,3.0,15.0,88.0,88.0,1.0,1.0,2.0,1.0,9999,0508
773,1,3,22,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,9999
777,1,1,22,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,0505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431704,6,11,5,2018,1100,1.0,10.0,88.0,88.0,1.0,1.0,1.0,1.0,9999,9999
431715,6,11,1,2018,1200,3.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,9999,9999
431766,6,12,10,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,0505
431803,6,11,20,2018,1100,4.0,99.0,99.0,99.0,1.0,2.0,2.0,1.0,9999,9999
431808,6,12,10,2018,1200,1.0,7.0,88.0,88.0,1.0,1.0,2.0,1.0,9999,0508
431814,6,12,6,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,0406
431962,6,10,23,2018,1100,4.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,9999
432005,6,12,3,2018,1200,1.0,88.0,88.0,NaN,1.0,2.0,2.0,4.0,9999,NaN
432257,6,5,31,2018,1200,3.0,1.0,5.0,88.0,1.0,3.0,2.0,1.0,9999,NaN
432272,6,5,12,2018,1100,4.0,88.0,88.0,NaN,1.0,3.0,2.0,3.0,9999,0509
432276,6,5,7,2018,1100,2.0,88.0,1.0,88.0,1.0,1.0,2.0,1.0,9999,0506
432319,6,6,9,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,0504
432404,6,10,8,2018,1200,3.0,88.0,88.0,NaN,1.0,3.0,2.0,1.0,9999,9999
432441,6,10,10,2018,1200,1.0,88.0,88.0,NaN,1.0,3.0,2.0,1.0,9999,0600
432466,6,11,5,2018,1100,3.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,9999,0502
432709,2,5,12,2018,1100,2.0,88.0,2.0,88.0,1.0,2.0,2.0,1.0,9999,0504
432987,2,8,21,2018,1100,3.0,15.0,25.0,88.0,1.0,1.0,2.0,1.0,9999,9999
433173,2,1,12,2019,1100,3.0,3.0,88.0,88.0,1.0,2.0,2.0,2.0,9999,0506
433642,2,3,8,2018,1100,2.0,88.0,88.0,NaN,2.0,1.0,2.0,1.0,9999,9999
434574,2,8,6,2018,1100,2.0,88.0,30.0,88.0,1.0,1.0,2.0,1.0,9999,9999
434690,2,9,2,2018,1100,3.0,88.0,88.0,NaN,2.0,3.0,2.0,7.0,9999,9999
434786,2,8,28,2018,1100,1.0,88.0,88.0,NaN,2.0,3.0,2.0,1.0,9999,9999
434811,2,8,26,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,1.0,1.0,9999,0600
434866,2,9,7,2018,1100,3.0,21.0,21.0,7.0,1.0,1.0,2.0,1.0,9999,9999
435059,2,10,3,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9999,9999
435118,2,10,11,2018,1100,4.0,30.0,30.0,30.0,1.0,2.0,2.0,1.0,9999,0504
435309,2,1,3,2019,1200,2.0,88.0,88.0,NaN,1.0,3.0,1.0,1.0,9999,9999
435647,2,12,28,2018,1100,3.0,14.0,30.0,88.0,1.0,3.0,2.0,2.0,9999,0503
436283,2,2,3,2019,1200,3.0,77.0,88.0,88.0,1.0,1.0,2.0,1.0,9999,9999
436491,2,2,19,2019,1100,3.0,88.0,88.0,NaN,1.0,3.0,2.0,1.0,9999,7777

The [`shape()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shape.html) property gives you the height and width of your DataFrame.

In [30]:
print(brfss.shape)
#Drop any rows without weight
brfss.dropna(subset=['WEIGHT2'], inplace=True)
print(brfss.shape[0])

(437436, 15)
430989

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.isin.html

In [16]:
brfss[np.isin(brfss['WEIGHT2'], ['7777', '9999'], invert=True)].shape

(408877, 15)

#### Derived Fields

In [31]:
brfss = brfss[np.isin(brfss['WEIGHT2'], ['7777', '9999'], invert=True)]
#Get rid of one questionable record:
brfss = brfss[~brfss.WEIGHT2.str.startswith('1')]

In [18]:
brfss['wtunit'] = brfss.WEIGHT2.str[0].astype(np.uint8)
brfss['wt'] = brfss.WEIGHT2.str[1:].astype(np.uint16)
brfss

,state,imonth,iday,iyear,dispcode,genhlth,physhlth,menthlth,poorhlth,hlthpln1,persdoc2,medcost,checkup1,WEIGHT2,HEIGHT3,wtunit,wt
0,1,1,5,2018,1100,2.0,30.0,88.0,30.0,1.0,1.0,2.0,1.0,0130,0504,0,130
1,1,1,12,2018,1100,3.0,88.0,88.0,NaN,2.0,1.0,1.0,2.0,0200,0505,0,200
2,1,1,8,2018,1100,5.0,10.0,88.0,88.0,1.0,1.0,2.0,1.0,0142,0410,0,142
3,1,1,3,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0190,0510,0,190
5,1,1,11,2018,1100,2.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0172,0502,0,172
6,1,1,10,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0150,0505,0,150
7,1,1,13,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0130,0505,0,130
8,1,1,9,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0205,0601,0,205
9,1,1,10,2018,1100,3.0,5.0,88.0,88.0,1.0,1.0,2.0,1.0,0151,0503,0,151
10,1,1,10,2018,1100,1.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0199,0600,0,199
11,1,1,3,2018,1100,3.0,7.0,2.0,88.0,1.0,1.0,2.0,1.0,0170,0503,0,170
12,1,1,11,2018,1100,2.0,2.0,1.0,88.0,2.0,3.0,1.0,1.0,0160,0503,0,160
13,1,1,12,2018,1100,4.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0200,0504,0,200
14,1,1,25,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0285,0511,0,285
15,1,1,19,2018,1100,3.0,5.0,88.0,10.0,1.0,1.0,9.0,1.0,0217,0506,0,217
16,1,1,10,2018,1100,3.0,77.0,88.0,88.0,1.0,1.0,2.0,1.0,0230,0509,0,230
17,1,1,18,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0250,0601,0,250
18,1,1,11,2018,1100,3.0,88.0,88.0,NaN,1.0,3.0,2.0,3.0,0155,0504,0,155
19,1,1,18,2018,1200,2.0,2.0,2.0,88.0,1.0,1.0,2.0,1.0,0138,0504,0,138
20,1,1,5,2018,1100,2.0,88.0,3.0,88.0,2.0,1.0,2.0,1.0,0240,0507,0,240
21,1,1,3,2018,1100,3.0,88.0,30.0,88.0,2.0,1.0,2.0,1.0,0240,0504,0,240
22,1,1,10,2018,1100,5.0,30.0,88.0,88.0,1.0,2.0,2.0,1.0,0185,0505,0,185
23,1,1,11,2018,1100,3.0,88.0,88.0,NaN,2.0,3.0,2.0,4.0,0165,0509,0,165
24,1,1,11,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,7.0,0131,0504,0,131
25,1,1,10,2018,1100,5.0,30.0,88.0,15.0,1.0,1.0,2.0,1.0,0119,0502,0,119
26,1,1,3,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0180,0505,0,180
27,1,1,8,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,2.0,0169,0506,0,169
28,1,1,10,2018,1100,2.0,3.0,88.0,88.0,1.0,1.0,2.0,1.0,0128,0506,0,128
29,1,1,10,2018,1100,3.0,2.0,15.0,88.0,1.0,1.0,2.0,1.0,0218,0603,0,218
30,1,1,18,2018,1100,3.0,5.0,88.0,30.0,1.0,1.0,2.0,1.0,0148,0502,0,148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437404,2,2,28,2019,1100,4.0,30.0,30.0,30.0,1.0,1.0,2.0,1.0,0108,0503,0,108
437405,2,3,1,2019,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0177,0503,0,177
437407,2,3,12,2019,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0320,0603,0,320
437408,2,2,25,2019,1100,3.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0125,0501,0,125
437409,2,3,23,2019,1100,4.0,30.0,30.0,88.0,1.0,3.0,2.0,1.0,0158,0505,0,158
437410,2,3,21,2019,1100,4.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0155,0502,0,155
437411,2,3,23,2019,1100,4.0,3.0,88.0,88.0,1.0,1.0,2.0,1.0,0150,0506,0,150
437412,2,3,2,2019,1100,3.0,1.0,88.0,88.0,1.0,3.0,2.0,2.0,0138,0502,0,138
437413,2,2,27,2019,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0135,0506,0,135
437414,2,3,22,2019,1100,2.0,88.0,88.0,NaN,1.0,3.0,2.0,3.0,0178,0506,0,178
437415,2,3,26,2019,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0126,0506,0,126
437416,2,2,27,2019,1100,1.0,88.0,15.0,88.0,1.0,1.0,2.0,1.0,0115,0411,0,115
437417,2,3,10,2019,1100,3.0,2.0,88.0,88.0,1.0,1.0,2.0,1.0,0183,0503,0,183
437418,2,2,23,2019,1100,3.0,7.0,88.0,7.0,1.0,1.0,1.0,1.0,0153,0504,0,153
437419,2,2,27,2019,1100,4.0,3.0,88.0,8.0,1.0,3.0,2.0,1.0,0138,0500,0,138
437420,2,3,12,2019,1100,4.0,30.0,77.0,15.0,1.0,1.0,1.0,1.0,0260,0503,0,260
437421,2,2,26,2019,1100,3.0,5.0,2.0,88.0,1.0,1.0,2.0,1.0,0160,0507,0,160
437422,2,2,26,2019,1100,4.0,14.0,10.0,14.0,1.0,1.0,2.0,2.0,0200,0601,0,200
437423,2,3,12,2019,1100,4.0,88.0,88.0,NaN,1.0,1.0,1.0,1.0,0126,0500,0,126
437424,2,3,19,2019,1100,4.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0340,0507,0,340
437425,2,3,12,2019,1100,4.0,4.0,88.0,88.0,1.0,3.0,2.0,1.0,0298,0600,0,298
437426,2,3,22,2019,1100,1.0,3.0,88.0,2.0,1.0,1.0,2.0,1.0,0160,0508,0,160
437427,2,2,27,2019,1100,4.0,20.0,88.0,5.0,1.0,1.0,2.0,1.0,0160,0506,0,160
437428,2,3,26,2019,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0163,0502,0,163
437429,2,3,12,2019,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0172,0508,0,172
437430,2,2,28,2019,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0170,0503,0,170
437431,2,3,19,2019,1100,1.0,88.0,30.0,88.0,1.0,1.0,2.0,1.0,0098,0502,0,98
437433,2,3,9,2019,1100,5.0,30.0,88.0,30.0,1.0,1.0,2.0,2.0,0156,0500,0,156
437434,2,3,22,2019,1100,4.0,88.0,2.0,88.0,1.0,1.0,2.0,1.0,0137,0501,0,137
437435,2,3,10,2019,1100,3.0,88.0,30.0,5.0,1.0,3.0,2.0,1.0,0192,0510,0,192

[`np.where()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html) provides the equivalent of an *if-then-else* statement on each observation in a DataFrame:

In [19]:
lbsperkg = 2.205
brfss['wtlbs'] = np.where(brfss.wtunit==9, brfss.wt*lbsperkg, brfss.wt).astype(np.int16)

In [20]:
brfss[brfss.wtunit==9]

,state,imonth,iday,iyear,dispcode,genhlth,physhlth,menthlth,poorhlth,hlthpln1,persdoc2,medcost,checkup1,WEIGHT2,HEIGHT3,wtunit,wt,wtlbs
2732,1,3,27,2018,1100,3.0,88.0,88.0,NaN,1.0,3.0,2.0,1.0,9070,9170,9,70,154
5182,1,9,26,2018,1100,2.0,88.0,88.0,NaN,1.0,7.0,2.0,1.0,9055,0505,9,55,121
8442,2,6,4,2018,1100,4.0,30.0,30.0,88.0,1.0,1.0,2.0,1.0,9067,0507,9,67,147
9092,2,10,30,2018,1100,2.0,1.0,88.0,88.0,9.0,1.0,2.0,2.0,9112,0509,9,112,246
10312,4,8,7,2018,1100,2.0,14.0,88.0,88.0,1.0,1.0,2.0,1.0,9089,0505,9,89,196
10404,4,10,4,2018,1100,4.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9120,0600,9,120,264
10780,4,1,24,2018,1100,3.0,88.0,88.0,NaN,1.0,3.0,2.0,3.0,9065,9168,9,65,143
11404,4,7,9,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9071,7777,9,71,156
11773,4,12,2,2018,1100,2.0,88.0,88.0,NaN,2.0,3.0,2.0,2.0,9073,7777,9,73,160
13098,4,2,15,2018,1100,1.0,88.0,88.0,NaN,2.0,3.0,2.0,3.0,9050,0508,9,50,110
13124,4,2,7,2018,1100,1.0,88.0,88.0,NaN,2.0,3.0,2.0,1.0,9050,9160,9,50,110
13176,4,2,11,2018,1100,1.0,88.0,88.0,NaN,2.0,3.0,2.0,3.0,9090,9176,9,90,198
13199,4,2,11,2018,1100,4.0,88.0,88.0,NaN,2.0,3.0,2.0,8.0,9058,7777,9,58,127
13357,4,3,30,2018,1100,1.0,88.0,3.0,88.0,1.0,1.0,1.0,8.0,9076,0600,9,76,167
13380,4,3,18,2018,1100,4.0,3.0,77.0,1.0,1.0,3.0,1.0,1.0,9076,9170,9,76,167
13759,4,4,13,2018,1100,1.0,88.0,88.0,NaN,1.0,3.0,2.0,2.0,9085,9163,9,85,187
13960,4,7,3,2018,1200,4.0,2.0,88.0,88.0,1.0,1.0,2.0,1.0,9080,9180,9,80,176
14365,4,8,8,2018,1100,3.0,88.0,88.0,NaN,2.0,3.0,2.0,1.0,9077,9162,9,77,169
14366,4,8,9,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9108,0508,9,108,238
14415,4,8,7,2018,1100,1.0,88.0,88.0,NaN,2.0,1.0,2.0,1.0,9078,9170,9,78,171
14599,4,10,1,2018,1100,4.0,15.0,88.0,88.0,2.0,3.0,1.0,2.0,9040,9152,9,40,88
14640,4,10,23,2018,1100,4.0,2.0,1.0,88.0,1.0,3.0,2.0,8.0,9080,9180,9,80,176
14844,4,10,18,2018,1100,3.0,2.0,1.0,88.0,2.0,1.0,1.0,2.0,9072,9175,9,72,158
14896,4,11,19,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9080,9179,9,80,176
15001,4,11,7,2018,1100,5.0,30.0,30.0,88.0,1.0,1.0,2.0,1.0,9067,0511,9,67,147
15073,4,12,27,2018,1100,5.0,7.0,88.0,88.0,1.0,7.0,2.0,1.0,9072,7777,9,72,158
15672,4,3,18,2018,1100,4.0,6.0,6.0,7.0,2.0,3.0,1.0,1.0,9070,7777,9,70,154
16451,4,6,15,2018,1100,3.0,15.0,88.0,14.0,1.0,3.0,2.0,1.0,9088,7777,9,88,194
16481,4,7,18,2018,1100,4.0,88.0,88.0,NaN,2.0,3.0,2.0,3.0,9074,9177,9,74,163
16905,4,9,8,2018,1100,2.0,88.0,15.0,2.0,1.0,1.0,2.0,2.0,9099,0509,9,99,218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423401,5,8,13,2018,1200,2.0,88.0,88.0,NaN,2.0,3.0,2.0,2.0,9065,9999,9,65,143
423440,5,1,11,2019,1200,3.0,88.0,88.0,NaN,1.0,1.0,2.0,2.0,9055,9175,9,55,121
424002,5,3,1,2018,1100,1.0,88.0,88.0,NaN,1.0,3.0,2.0,2.0,9060,0503,9,60,132
424296,5,3,21,2018,1100,3.0,88.0,88.0,NaN,2.0,1.0,2.0,1.0,9175,0500,9,175,385
424329,5,3,26,2018,1200,3.0,88.0,88.0,NaN,2.0,3.0,2.0,1.0,9180,0504,9,180,396
424390,5,4,29,2018,1200,2.0,1.0,88.0,88.0,1.0,2.0,1.0,8.0,9086,0602,9,86,189
424459,5,4,10,2018,1100,3.0,88.0,88.0,NaN,2.0,3.0,2.0,3.0,9060,9170,9,60,132
424990,5,7,8,2018,1100,4.0,14.0,88.0,14.0,2.0,3.0,2.0,2.0,9070,0506,9,70,154
425141,5,7,12,2018,1100,4.0,30.0,30.0,30.0,1.0,1.0,2.0,1.0,9142,0506,9,142,313
425563,5,8,3,2018,1100,4.0,5.0,8.0,88.0,2.0,3.0,1.0,3.0,9070,9999,9,70,154
425621,5,9,1,2018,1200,2.0,88.0,10.0,88.0,1.0,1.0,2.0,1.0,9053,0503,9,53,116
425814,5,9,8,2018,1100,1.0,1.0,88.0,88.0,1.0,1.0,2.0,1.0,9081,9182,9,81,178
426243,5,11,20,2018,1100,3.0,88.0,10.0,88.0,1.0,1.0,2.0,1.0,9063,9176,9,63,138
426436,5,12,15,2018,1100,2.0,77.0,88.0,88.0,1.0,1.0,2.0,1.0,9079,9166,9,79,174
430311,6,9,9,2018,1100,5.0,30.0,30.0,30.0,1.0,2.0,1.0,2.0,9067,0508,9,67,147
430803,6,12,4,2018,1100,2.0,88.0,88.0,NaN,2.0,1.0,2.0,2.0,9084,0511,9,84,185
431170,6,4,19,2018,1100,1.0,88.0,88.0,NaN,1.0,3.0,2.0,2.0,9065,0500,9,65,143
431206,6,4,19,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,9025,0409,9,25,55
431238,6,5,19,2018,1100,4.0,7.0,30.0,15.0,1.0,1.0,1.0,1.0,9128,0505,9,128,282
431320,6,6,18,2018,1100,3.0,4.0,88.0,4.0,1.0,2.0,2.0,1.0,9057,0503,9,57,125
431372,6,6,13,2018,1100,3.0,5.0,3.0,88.0,1.0,1.0,2.0,1.0,9054,0504,9,54,119
431392,6,7,25,2018,1100,3.0,99.0,99.0,77.0,2.0,3.0,2.0,1.0,9060,9174,9,60,132
431509,6,8,14,2018,1100,2.0,1.0,88.0,88.0,2.0,3.0,2.0,2.0,9055,0500,9,55,121
431587,6,8,7,2018,1100,4.0,7.0,88.0,88.0,1.0,1.0,2.0,1.0,9064,0503,9,64,141
431753,6,11,5,2018,1100,1.0,88.0,88.0,NaN,2.0,3.0,2.0,1.0,9075,0605,9,75,165
432349,6,7,31,2018,1200,1.0,88.0,88.0,NaN,2.0,1.0,2.0,1.0,9062,0505,9,62,136
432405,6,9,29,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,4.0,9053,9160,9,53,116
432468,6,10,24,2018,1100,2.0,88.0,88.0,NaN,1.0,3.0,2.0,1.0,9065,0507,9,65,143
432498,6,12,17,2018,1100,3.0,88.0,88.0,NaN,1.0,3.0,2.0,1.0,9080,9170,9,80,176
432588,6,1,12,2019,1200,1.0,88.0,88.0,NaN,1.0,3.0,2.0,3.0,9070,0504,9,70,154

##### Practice

Create a `htinches` column from the `brfss.HEIGHT3` column. 

1. Remove rows where `HEIGHT3` is 7777 ("Don't know/Not sure"),  9999 ("Refused"), or NaN.
2. If the first character of `HEIGHT3` is '9', multiply the remaining three digits by `cmtoin` (defined below) to get height in inches.
3. If the first character of `HEIGHT3` is '0', the second character is feet, and the third and fourth are inches ('0601' means six feet, one inch). Convert this to inches.

See page 36 of the codebook for details on the `HEIGHT3` field.

In [21]:
cmtoin = 0.3937

In [53]:
brfss.dropna(subset=['HEIGHT3'], inplace=True)

brfss['htunit'] = brfss.HEIGHT3.str[0].astype(np.uint16)
brfss['ht'] = brfss.HEIGHT3.str[1:]

feet = brfss.ht.str[0].astype(np.uint8)
inches = brfss.ht.str[1:].astype(np.uint8)
inches = inches + (feet * 12)
brfss['htinches'] = np.where(brfss.htunit==0, inches, brfss.ht)

#NOTE: Should also drop HEIGHT3==9999

#### Summary statistics and aggregation

In [57]:
# | means 'or'
# ph=1 if you were sick more than 5 days, 0 otherwise:
brfss['ph'] = np.where((brfss['poorhlth'] > 30) | 
                       (brfss['poorhlth'] <= 5) | 
                       (brfss['poorhlth'].isnull()), 0, 1)
brfss

,state,imonth,iday,iyear,dispcode,genhlth,physhlth,menthlth,poorhlth,hlthpln1,persdoc2,medcost,checkup1,WEIGHT2,HEIGHT3,htunit,ht,htinches,ph
0,1,1,5,2018,1100,2.0,30.0,88.0,30.0,1.0,1.0,2.0,1.0,0130,0504,0,504,64,1
1,1,1,12,2018,1100,3.0,88.0,88.0,NaN,2.0,1.0,1.0,2.0,0200,0505,0,505,65,0
2,1,1,8,2018,1100,5.0,10.0,88.0,88.0,1.0,1.0,2.0,1.0,0142,0410,0,410,58,0
3,1,1,3,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0190,0510,0,510,70,0
5,1,1,11,2018,1100,2.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0172,0502,0,502,62,0
6,1,1,10,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0150,0505,0,505,65,0
7,1,1,13,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0130,0505,0,505,65,0
8,1,1,9,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0205,0601,0,601,73,0
9,1,1,10,2018,1100,3.0,5.0,88.0,88.0,1.0,1.0,2.0,1.0,0151,0503,0,503,63,0
10,1,1,10,2018,1100,1.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0199,0600,0,600,72,0
11,1,1,3,2018,1100,3.0,7.0,2.0,88.0,1.0,1.0,2.0,1.0,0170,0503,0,503,63,0
12,1,1,11,2018,1100,2.0,2.0,1.0,88.0,2.0,3.0,1.0,1.0,0160,0503,0,503,63,0
13,1,1,12,2018,1100,4.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0200,0504,0,504,64,0
14,1,1,25,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0285,0511,0,511,71,0
15,1,1,19,2018,1100,3.0,5.0,88.0,10.0,1.0,1.0,9.0,1.0,0217,0506,0,506,66,1
16,1,1,10,2018,1100,3.0,77.0,88.0,88.0,1.0,1.0,2.0,1.0,0230,0509,0,509,69,0
17,1,1,18,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0250,0601,0,601,73,0
18,1,1,11,2018,1100,3.0,88.0,88.0,NaN,1.0,3.0,2.0,3.0,0155,0504,0,504,64,0
19,1,1,18,2018,1200,2.0,2.0,2.0,88.0,1.0,1.0,2.0,1.0,0138,0504,0,504,64,0
20,1,1,5,2018,1100,2.0,88.0,3.0,88.0,2.0,1.0,2.0,1.0,0240,0507,0,507,67,0
21,1,1,3,2018,1100,3.0,88.0,30.0,88.0,2.0,1.0,2.0,1.0,0240,0504,0,504,64,0
22,1,1,10,2018,1100,5.0,30.0,88.0,88.0,1.0,2.0,2.0,1.0,0185,0505,0,505,65,0
23,1,1,11,2018,1100,3.0,88.0,88.0,NaN,2.0,3.0,2.0,4.0,0165,0509,0,509,69,0
24,1,1,11,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,7.0,0131,0504,0,504,64,0
25,1,1,10,2018,1100,5.0,30.0,88.0,15.0,1.0,1.0,2.0,1.0,0119,0502,0,502,62,1
26,1,1,3,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0180,0505,0,505,65,0
27,1,1,8,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,2.0,0169,0506,0,506,66,0
28,1,1,10,2018,1100,2.0,3.0,88.0,88.0,1.0,1.0,2.0,1.0,0128,0506,0,506,66,0
29,1,1,10,2018,1100,3.0,2.0,15.0,88.0,1.0,1.0,2.0,1.0,0218,0603,0,603,75,0
30,1,1,18,2018,1100,3.0,5.0,88.0,30.0,1.0,1.0,2.0,1.0,0148,0502,0,502,62,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437404,2,2,28,2019,1100,4.0,30.0,30.0,30.0,1.0,1.0,2.0,1.0,0108,0503,0,503,63,1
437405,2,3,1,2019,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0177,0503,0,503,63,0
437407,2,3,12,2019,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0320,0603,0,603,75,0
437408,2,2,25,2019,1100,3.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0125,0501,0,501,61,0
437409,2,3,23,2019,1100,4.0,30.0,30.0,88.0,1.0,3.0,2.0,1.0,0158,0505,0,505,65,0
437410,2,3,21,2019,1100,4.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0155,0502,0,502,62,0
437411,2,3,23,2019,1100,4.0,3.0,88.0,88.0,1.0,1.0,2.0,1.0,0150,0506,0,506,66,0
437412,2,3,2,2019,1100,3.0,1.0,88.0,88.0,1.0,3.0,2.0,2.0,0138,0502,0,502,62,0
437413,2,2,27,2019,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0135,0506,0,506,66,0
437414,2,3,22,2019,1100,2.0,88.0,88.0,NaN,1.0,3.0,2.0,3.0,0178,0506,0,506,66,0
437415,2,3,26,2019,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0126,0506,0,506,66,0
437416,2,2,27,2019,1100,1.0,88.0,15.0,88.0,1.0,1.0,2.0,1.0,0115,0411,0,411,59,0
437417,2,3,10,2019,1100,3.0,2.0,88.0,88.0,1.0,1.0,2.0,1.0,0183,0503,0,503,63,0
437418,2,2,23,2019,1100,3.0,7.0,88.0,7.0,1.0,1.0,1.0,1.0,0153,0504,0,504,64,1
437419,2,2,27,2019,1100,4.0,3.0,88.0,8.0,1.0,3.0,2.0,1.0,0138,0500,0,500,60,1
437420,2,3,12,2019,1100,4.0,30.0,77.0,15.0,1.0,1.0,1.0,1.0,0260,0503,0,503,63,1
437421,2,2,26,2019,1100,3.0,5.0,2.0,88.0,1.0,1.0,2.0,1.0,0160,0507,0,507,67,0
437422,2,2,26,2019,1100,4.0,14.0,10.0,14.0,1.0,1.0,2.0,2.0,0200,0601,0,601,73,1
437423,2,3,12,2019,1100,4.0,88.0,88.0,NaN,1.0,1.0,1.0,1.0,0126,0500,0,500,60,0
437424,2,3,19,2019,1100,4.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0340,0507,0,507,67,0
437425,2,3,12,2019,1100,4.0,4.0,88.0,88.0,1.0,3.0,2.0,1.0,0298,0600,0,600,72,0
437426,2,3,22,2019,1100,1.0,3.0,88.0,2.0,1.0,1.0,2.0,1.0,0160,0508,0,508,68,0
437427,2,2,27,2019,1100,4.0,20.0,88.0,5.0,1.0,1.0,2.0,1.0,0160,0506,0,506,66,0
437428,2,3,26,2019,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0163,0502,0,502,62,0
437429,2,3,12,2019,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0172,0508,0,508,68,0
437430,2,2,28,2019,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0170,0503,0,503,63,0
437431,2,3,19,2019,1100,1.0,88.0,30.0,88.0,1.0,1.0,2.0,1.0,0098,0502,0,502,62,0
437433,2,3,9,2019,1100,5.0,30.0,88.0,30.0,1.0,1.0,2.0,2.0,0156,0500,0,500,60,1
437434,2,3,22,2019,1100,4.0,88.0,2.0,88.0,1.0,1.0,2.0,1.0,0137,0501,0,501,61,0
437435,2,3,10,2019,1100,3.0,88.0,30.0,5.0,1.0,3.0,2.0,1.0,0192,0510,0,510,70,0

In [59]:
#brfss.groupby(['persdoc2', 'ph']).describe()
brfss.groupby(brfss.persdoc2).size()

persdoc2
1.0    306316
2.0     31838
3.0     67879
7.0      1282
9.0       306
dtype: int64

In [85]:
brfss.groupby(['persdoc2', 'ph']).median() #size() #or .mean()

             state  imonth  iday   iyear  dispcode  genhlth  physhlth  \
persdoc2 ph
1.0      0     5.0     7.0  14.0  2018.0    1100.0      2.0      88.0
         1     5.0     7.0  14.0  2018.0    1100.0      4.0      29.0
2.0      0     5.0     7.0  14.0  2018.0    1100.0      3.0      88.0
         1     5.0     7.0  14.0  2018.0    1100.0      4.0      30.0
3.0      0     5.0     7.0  15.0  2018.0    1100.0      2.0      88.0
         1     5.0     7.0  15.0  2018.0    1100.0      4.0      30.0
7.0      0     5.0     7.0  14.0  2018.0    1100.0      3.0      88.0
         1     4.0     6.0  13.0  2018.0    1100.0      4.0      30.0
9.0      0     6.0     7.0  15.0  2018.0    1100.0      3.0      88.0
         1     4.5     7.0  12.5  2018.0    1100.0      4.0      30.0

             menthlth  poorhlth  hlthpln1  medcost  checkup1  htunit
persdoc2 ph
1.0      0       88.0      51.0       1.0      2.0       1.0       0
         1       30.0      20.0       1.0      2.0       1.0       0
2.0      0       88.0      51.0       1.0      2.0       1.0       0
         1       30.0      20.0       1.0      2.0       1.0       0
3.0      0       88.0      51.0       1.0      2.0       2.0       0
         1       30.0      15.0       1.0      2.0       2.0       0
7.0      0       88.0      51.0       1.0      2.0       1.0       0
         1       30.0      20.0       1.0      2.0       1.0       0
9.0      0       88.0      51.0       1.0      2.0       1.0       0
         1       53.5      20.0       1.0      2.0       1.0       0

In [62]:
#Calculate percentages instead of raw numbers.
docph = brfss.groupby(['persdoc2', 'ph']).size()
docph.groupby(level=0).apply(lambda x: 100 * x / float(x.sum()))

persdoc2  ph
1.0       0     87.356847
          1     12.643153
2.0       0     80.403920
          1     19.596080
3.0       0     89.661014
          1     10.338986
7.0       0     87.753510
          1     12.246490
9.0       0     86.928105
          1     13.071895
dtype: float64

We can bin or categorize numeric variables with [`pd.cut()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html).

In [63]:
## 88 means 'none'; want to bin it separately from "Don't know" and "refused"
brfss.loc[brfss.poorhlth==88, 'poorhlth']=51
bins = [1, 5, 10, 20, 30, 51, 70]
brfss['phcats'] = pd.cut(brfss.poorhlth, bins, 
                         labels=['less than 5', 'less than 10', 
                                 'less than 20', 'more than 20', 'none', "don't know/refused"])
brfss

,state,imonth,iday,iyear,dispcode,genhlth,physhlth,menthlth,poorhlth,hlthpln1,persdoc2,medcost,checkup1,WEIGHT2,HEIGHT3,htunit,ht,htinches,ph,phcats
0,1,1,5,2018,1100,2.0,30.0,88.0,30.0,1.0,1.0,2.0,1.0,0130,0504,0,504,64,1,more than 20
1,1,1,12,2018,1100,3.0,88.0,88.0,NaN,2.0,1.0,1.0,2.0,0200,0505,0,505,65,0,NaN
2,1,1,8,2018,1100,5.0,10.0,88.0,51.0,1.0,1.0,2.0,1.0,0142,0410,0,410,58,0,none
3,1,1,3,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0190,0510,0,510,70,0,NaN
5,1,1,11,2018,1100,2.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0172,0502,0,502,62,0,NaN
6,1,1,10,2018,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0150,0505,0,505,65,0,NaN
7,1,1,13,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0130,0505,0,505,65,0,NaN
8,1,1,9,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0205,0601,0,601,73,0,NaN
9,1,1,10,2018,1100,3.0,5.0,88.0,51.0,1.0,1.0,2.0,1.0,0151,0503,0,503,63,0,none
10,1,1,10,2018,1100,1.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0199,0600,0,600,72,0,NaN
11,1,1,3,2018,1100,3.0,7.0,2.0,51.0,1.0,1.0,2.0,1.0,0170,0503,0,503,63,0,none
12,1,1,11,2018,1100,2.0,2.0,1.0,51.0,2.0,3.0,1.0,1.0,0160,0503,0,503,63,0,none
13,1,1,12,2018,1100,4.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0200,0504,0,504,64,0,NaN
14,1,1,25,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0285,0511,0,511,71,0,NaN
15,1,1,19,2018,1100,3.0,5.0,88.0,10.0,1.0,1.0,9.0,1.0,0217,0506,0,506,66,1,less than 10
16,1,1,10,2018,1100,3.0,77.0,88.0,51.0,1.0,1.0,2.0,1.0,0230,0509,0,509,69,0,none
17,1,1,18,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0250,0601,0,601,73,0,NaN
18,1,1,11,2018,1100,3.0,88.0,88.0,NaN,1.0,3.0,2.0,3.0,0155,0504,0,504,64,0,NaN
19,1,1,18,2018,1200,2.0,2.0,2.0,51.0,1.0,1.0,2.0,1.0,0138,0504,0,504,64,0,none
20,1,1,5,2018,1100,2.0,88.0,3.0,51.0,2.0,1.0,2.0,1.0,0240,0507,0,507,67,0,none
21,1,1,3,2018,1100,3.0,88.0,30.0,51.0,2.0,1.0,2.0,1.0,0240,0504,0,504,64,0,none
22,1,1,10,2018,1100,5.0,30.0,88.0,51.0,1.0,2.0,2.0,1.0,0185,0505,0,505,65,0,none
23,1,1,11,2018,1100,3.0,88.0,88.0,NaN,2.0,3.0,2.0,4.0,0165,0509,0,509,69,0,NaN
24,1,1,11,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,7.0,0131,0504,0,504,64,0,NaN
25,1,1,10,2018,1100,5.0,30.0,88.0,15.0,1.0,1.0,2.0,1.0,0119,0502,0,502,62,1,less than 20
26,1,1,3,2018,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0180,0505,0,505,65,0,NaN
27,1,1,8,2018,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,2.0,0169,0506,0,506,66,0,NaN
28,1,1,10,2018,1100,2.0,3.0,88.0,51.0,1.0,1.0,2.0,1.0,0128,0506,0,506,66,0,none
29,1,1,10,2018,1100,3.0,2.0,15.0,51.0,1.0,1.0,2.0,1.0,0218,0603,0,603,75,0,none
30,1,1,18,2018,1100,3.0,5.0,88.0,30.0,1.0,1.0,2.0,1.0,0148,0502,0,502,62,1,more than 20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437404,2,2,28,2019,1100,4.0,30.0,30.0,30.0,1.0,1.0,2.0,1.0,0108,0503,0,503,63,1,more than 20
437405,2,3,1,2019,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0177,0503,0,503,63,0,NaN
437407,2,3,12,2019,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0320,0603,0,603,75,0,NaN
437408,2,2,25,2019,1100,3.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0125,0501,0,501,61,0,NaN
437409,2,3,23,2019,1100,4.0,30.0,30.0,51.0,1.0,3.0,2.0,1.0,0158,0505,0,505,65,0,none
437410,2,3,21,2019,1100,4.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0155,0502,0,502,62,0,NaN
437411,2,3,23,2019,1100,4.0,3.0,88.0,51.0,1.0,1.0,2.0,1.0,0150,0506,0,506,66,0,none
437412,2,3,2,2019,1100,3.0,1.0,88.0,51.0,1.0,3.0,2.0,2.0,0138,0502,0,502,62,0,none
437413,2,2,27,2019,1100,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0135,0506,0,506,66,0,NaN
437414,2,3,22,2019,1100,2.0,88.0,88.0,NaN,1.0,3.0,2.0,3.0,0178,0506,0,506,66,0,NaN
437415,2,3,26,2019,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0126,0506,0,506,66,0,NaN
437416,2,2,27,2019,1100,1.0,88.0,15.0,51.0,1.0,1.0,2.0,1.0,0115,0411,0,411,59,0,none
437417,2,3,10,2019,1100,3.0,2.0,88.0,51.0,1.0,1.0,2.0,1.0,0183,0503,0,503,63,0,none
437418,2,2,23,2019,1100,3.0,7.0,88.0,7.0,1.0,1.0,1.0,1.0,0153,0504,0,504,64,1,less than 10
437419,2,2,27,2019,1100,4.0,3.0,88.0,8.0,1.0,3.0,2.0,1.0,0138,0500,0,500,60,1,less than 10
437420,2,3,12,2019,1100,4.0,30.0,77.0,15.0,1.0,1.0,1.0,1.0,0260,0503,0,503,63,1,less than 20
437421,2,2,26,2019,1100,3.0,5.0,2.0,51.0,1.0,1.0,2.0,1.0,0160,0507,0,507,67,0,none
437422,2,2,26,2019,1100,4.0,14.0,10.0,14.0,1.0,1.0,2.0,2.0,0200,0601,0,601,73,1,less than 20
437423,2,3,12,2019,1100,4.0,88.0,88.0,NaN,1.0,1.0,1.0,1.0,0126,0500,0,500,60,0,NaN
437424,2,3,19,2019,1100,4.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,0340,0507,0,507,67,0,NaN
437425,2,3,12,2019,1100,4.0,4.0,88.0,51.0,1.0,3.0,2.0,1.0,0298,0600,0,600,72,0,none
437426,2,3,22,2019,1100,1.0,3.0,88.0,2.0,1.0,1.0,2.0,1.0,0160,0508,0,508,68,0,less than 5
437427,2,2,27,2019,1100,4.0,20.0,88.0,5.0,1.0,1.0,2.0,1.0,0160,0506,0,506,66,0,less than 5
437428,2,3,26,2019,1100,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0163,0502,0,502,62,0,NaN
437429,2,3,12,2019,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0172,0508,0,508,68,0,NaN
437430,2,2,28,2019,1100,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,0170,0503,0,503,63,0,NaN
437431,2,3,19,2019,1100,1.0,88.0,30.0,51.0,1.0,1.0,2.0,1.0,0098,0502,0,502,62,0,none
437433,2,3,9,2019,1100,5.0,30.0,88.0,30.0,1.0,1.0,2.0,2.0,0156,0500,0,500,60,1,more than 20
437434,2,3,22,2019,1100,4.0,88.0,2.0,51.0,1.0,1.0,2.0,1.0,0137,0501,0,501,61,0,none
437435,2,3,10,2019,1100,3.0,88.0,30.0,5.0,1.0,3.0,2.0,1.0,0192,0510,0,510,70,0,less than 5

##### Practice

1) Create a new column that divides `iday` into 3 bins (1-10, 11-20, 21+).

In [72]:
daygrp = pd.cut(brfss.iday, [0, 10, 20, 40])
daygrp

0          (0, 10]
1         (10, 20]
2          (0, 10]
3          (0, 10]
5         (10, 20]
6          (0, 10]
7         (10, 20]
8          (0, 10]
9          (0, 10]
10         (0, 10]
11         (0, 10]
12        (10, 20]
13        (10, 20]
14        (20, 40]
15        (10, 20]
16         (0, 10]
17        (10, 20]
18        (10, 20]
19        (10, 20]
20         (0, 10]
21         (0, 10]
22         (0, 10]
23        (10, 20]
24        (10, 20]
25         (0, 10]
26         (0, 10]
27         (0, 10]
28         (0, 10]
29         (0, 10]
30        (10, 20]
            ...
437404    (20, 40]
437405     (0, 10]
437407    (10, 20]
437408    (20, 40]
437409    (20, 40]
437410    (20, 40]
437411    (20, 40]
437412     (0, 10]
437413    (20, 40]
437414    (20, 40]
437415    (20, 40]
437416    (20, 40]
437417     (0, 10]
437418    (20, 40]
437419    (20, 40]
437420    (10, 20]
437421    (20, 40]
437422    (20, 40]
437423    (10, 20]
437424    (10, 20]
437425    (10, 20]
437426    (20, 40]
437427    (20, 40]
437428    (20, 40]
437429    (10, 20]
437430    (20, 40]
437431    (10, 20]
437433     (0, 10]
437434    (20, 40]
437435     (0, 10]
Name: iday, Length: 408436, dtype: category
Categories (3, interval[int64]): [(0, 10] < (10, 20] < (20, 40]]

2) Group `brfss` by `hlthpln1` and `medcost` and create a table like the one above (for `persdoc2` and `ph`) with percentages for each subgroup.

In [88]:
docph = brfss.groupby(['hlthpln1', 'medcost']).size()
docph.groupby(level=0).apply(lambda x: 100 * x / float(x.sum()))

hlthpln1  medcost
1.0       1.0         7.967329
          2.0        91.815023
          7.0         0.183649
          9.0         0.033999
2.0       1.0        36.719255
          2.0        62.788695
          7.0         0.427469
          9.0         0.064582
7.0       1.0        17.922794
          2.0        79.779412
          7.0         2.113971
          9.0         0.183824
9.0       1.0        11.320755
          2.0        84.905660
          7.0         0.419287
          9.0         3.354298
dtype: float64